apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: krakenclusters.samsung-cnct.com
spec:
  group: samsung-cnct.com
  version: v1
  scope: Namespaced
  names:
    plural: krakenclusters
    singular: krakencluster
    kind: KrakenCluster
    shortnames:
      - kc
  validation:
      openAPIV3Schema:
        properties:
          spec:
            required:
            - customerId
            - cloudProvider
            - provisioner
            - cluster
            properties:
              customerId:
                type: string
              cluster:
                type: object
                required:
                - clusterName
                - workers
                - masters
                - etcd
                - fabric
                properties:
                  clusterName:
                    type: string
                  workers:
                    type: object
                    required:
                    - size
                    - os
                    - machineType
                    - publicIPs
                    properties:
                      size:
                        type: integer
                      os:
                        type: string
                      machineType:
                        type: string
                      publicIps:
                        type: boolean
                  masters:
                    type: object
                    required:
                    - size
                    - os
                    - machineType
                    - publicIPs
                    properties:
                      size:
                        type: integer
                      os:
                        type: string
                      machineType:
                        type: string
                      publicIps:
                        type: boolean
                  etcd:
                    type: object
                    required:
                    - size
                    - os
                    - machineType
                    - publicIPs
                    properties:
                      size:
                        type: integer
                      os:
                        type: string
                      machineType:
                        type: string
                      publicIps:
                        type: boolean
                  fabric:
                    type: object
                    required:
                    - name
                    properties:
                      name:
                        type: string
              cloudProvider:
                type: object
                required:
                - name
                properties:
                  name:
                    type: string
                  credentials:
                    type: object
              provisioner:
                type: object
                required:
                - name
                properties:
                  name:
                   type: string
