# Default values for cluster-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
name: 

image:
  # repository: samsung_cnct/cluster-controller:latest
  repository: leahnp/cluster-test:latest
  # TODO version this
  # tag: lastest
  # pullPolicy: IfNotPresent
  pullPolicy: Always

krakenClusterShortNames: kc

service:
  type: ClusterIP
  internalPort: 80
  clientPort: 80
  replicas: 1
  cpu: 100m
  terminationGracePeriodSeconds: 30

storage:
  memory: 512Mi