# Default values for cluster-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  name: quay.io/samsung_cnct/cluster-controller:prod

  # if you develop locally, build the docker image and push to your repo
  # repository: leahnp/cluster-test:latest
  # TODO version this
  # tag: prod
  pullPolicy: Always

krakenClusterShortNames: kc

rbac:
  # If true, create & use RBAC resources
  create: true
  # Ignored if rbac.create is true
  serviceAccountName: default

service:
  type: ClusterIP
  internalPort: 80
  clientPort: 80
  replicas: 1
  cpu: 100m
  terminationGracePeriodSeconds: 30

storage:
  memory: 512Mi