apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-controller-deployment
  labels:
    app: cluster-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-controller
  template:
    metadata:
      labels:
        app: cluster-controller
    spec:
      containers:
      - name: cluster-controller
        image: leahnp/cluster-test:latest
        # TODO - why does this not work? w/ENTRYPOINT /bin/controller/main
        # command: ["/bin/controller/main"]
        # args:
        # - -kubeconfig=""
        ports:
        - containerPort: 80
