apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: krakenclusters.samsung-cnct.com
spec:
  group: samsung-cnct.com
  version: v1
  scope: Namespaced
  names:
    plural: krakenclusters
    singular: krakencluster
    kind: KrakenCluster
    shortnames:
      - kc
  validation:
      openAPIV3Schema:
        properties:
          spec:
            required:
            - customerID
            - cloudProvider
            - provisioner
            - cluster
            properties:
              customerID:
                type: string
              cluster:
                type: object
                required:
                - clusterName
                - fabric
                - nodePools
                properties:
                  clusterName:
                    type: string
                  nodePools:
                    type: array
                    items:
                      type: object
                      required:
                      - name
                      - size
                      - machineType
                      - os
                      properties:
                        name:
                          type: string
                        size:
                          type: integer
                        publicIPs:
                          type: boolean
                        machineType:
                          type: string
                        os:
                          type: string
                  fabric:
                    type: object
                    required:
                    - name
                    properties:
                      name:
                        type: string
              cloudProvider:
                type: object
                required:
                - name
                properties:
                  name:
                    type: string
                  credentials:
                    type: object
              provisioner:
                type: object
                required:
                - name
                properties:
                  name:
                   type: string
