---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: krakencluster-reader
  labels:
    app: {{ template "name" . }}
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: krakencluster-reader
  apiGroup: rbac.authorization.k8s.io 
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: krakencluster-writer
  labels:
    app: {{ template "name" . }}
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: krakencluster-writer
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: krakencluster-reader
  labels:
    app: {{ template "name" . }}
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 }}
rules:
- apiGroups: ["samsung.cnct.com"]
  resources: ["krakenclusters"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: krakencluster-writer
  labels:
    app: {{ template "name" . }}
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 }}
rules:
- apiGroups: ["samsung.cnct.com"]
  resources: ["krakenclusters", "events", "namespaces"]
  verbs: ["create", "update", "delete","edit","patch"]
- apiGroups: [""]
  resources: ["events", "namespaces"]
  verbs: ["create", "update", "delete","edit","patch"]